// data.js — Todos los partidos de la Fase de Grupos, Mundial FIFA 2026
// Formato: { day, time, home, away, group, venue }

const MATCHES = [
  // ── Jornada 1 ──
  { day: "Jue 11 jun", time: "15:00", home: "México",          away: "Sudáfrica",       group: "A", venue: "Cd. de México" },
  { day: "Jue 11 jun", time: "22:00", home: "Rep. de Corea",   away: "Rep. Checa",       group: "A", venue: "Guadalajara"    },
  { day: "Vie 12 jun", time: "15:00", home: "Canadá",          away: "Bosnia y Herz.",   group: "B", venue: "Toronto"        },
  { day: "Vie 12 jun", time: "21:00", home: "Estados Unidos",  away: "Paraguay",         group: "D", venue: "Los Ángeles"    },
  { day: "Sáb 13 jun", time: "15:00", home: "Catar",           away: "Suiza",            group: "B", venue: "San Francisco"  },
  { day: "Sáb 13 jun", time: "18:00", home: "Brasil",          away: "Marruecos",        group: "C", venue: "Nueva York/NJ"  },
  { day: "Sáb 13 jun", time: "21:00", home: "Haití",           away: "Escocia",          group: "C", venue: "Boston"         },
  { day: "Sáb 13 jun", time: "00:00", home: "Australia",       away: "Turquía",          group: "D", venue: "Vancouver"      },
  { day: "Dom 14 jun", time: "13:00", home: "Alemania",        away: "Curazao",          group: "E", venue: "Houston"        },
  { day: "Dom 14 jun", time: "16:00", home: "Países Bajos",    away: "Japón",            group: "F", venue: "Dallas"         },
  { day: "Dom 14 jun", time: "19:00", home: "Costa de Marfil", away: "Ecuador",          group: "E", venue: "Filadelfia"     },
  { day: "Dom 14 jun", time: "22:00", home: "Suecia",          away: "Túnez",            group: "F", venue: "Monterrey"      },
  { day: "Lun 15 jun", time: "12:00", home: "España",          away: "Cabo Verde",       group: "H", venue: "Atlanta"        },
  { day: "Lun 15 jun", time: "15:00", home: "Bélgica",         away: "Egipto",           group: "G", venue: "Seattle"        },
  { day: "Lun 15 jun", time: "18:00", home: "Arabia Saudí",    away: "Uruguay",          group: "H", venue: "Miami"          },
  { day: "Lun 15 jun", time: "21:00", home: "Irán",            away: "Nueva Zelanda",    group: "G", venue: "Los Ángeles"    },
  { day: "Mar 16 jun", time: "15:00", home: "Francia",         away: "Senegal",          group: "I", venue: "Nueva York/NJ"  },
  { day: "Mar 16 jun", time: "18:00", home: "Irak",            away: "Noruega",          group: "I", venue: "Boston"         },
  { day: "Mar 16 jun", time: "21:00", home: "Argentina",       away: "Argelia",          group: "J", venue: "Kansas City"    },
  { day: "Mar 16 jun", time: "00:00", home: "Austria",         away: "Jordania",         group: "J", venue: "San Francisco"  },
  { day: "Mié 17 jun", time: "13:00", home: "Portugal",        away: "RD Congo",         group: "K", venue: "Houston"        },
  { day: "Mié 17 jun", time: "16:00", home: "Inglaterra",      away: "Croacia",          group: "L", venue: "Dallas"         },
  { day: "Mié 17 jun", time: "19:00", home: "Ghana",           away: "Panamá",           group: "L", venue: "Toronto"        },
  { day: "Mié 17 jun", time: "22:00", home: "Uzbekistán",      away: "Colombia",         group: "K", venue: "Cd. de México"  },

  // ── Jornada 2 ──
  { day: "Jue 18 jun", time: "12:00", home: "Rep. Checa",      away: "Sudáfrica",        group: "A", venue: "Atlanta"        },
  { day: "Jue 18 jun", time: "15:00", home: "Suiza",           away: "Bosnia y Herz.",   group: "B", venue: "Los Ángeles"    },
  { day: "Jue 18 jun", time: "18:00", home: "Canadá",          away: "Catar",            group: "B", venue: "Vancouver"      },
  { day: "Jue 18 jun", time: "21:00", home: "México",          away: "Rep. de Corea",    group: "A", venue: "Guadalajara"    },
  { day: "Vie 19 jun", time: "15:00", home: "Estados Unidos",  away: "Australia",        group: "D", venue: "Seattle"        },
  { day: "Vie 19 jun", time: "18:00", home: "Escocia",         away: "Marruecos",        group: "C", venue: "Boston"         },
  { day: "Vie 19 jun", time: "21:00", home: "Brasil",          away: "Haití",            group: "C", venue: "Filadelfia"     },
  { day: "Vie 19 jun", time: "00:00", home: "Turquía",         away: "Paraguay",         group: "D", venue: "San Francisco"  },
  { day: "Sáb 20 jun", time: "13:00", home: "Países Bajos",   away: "Suecia",            group: "F", venue: "Houston"        },
  { day: "Sáb 20 jun", time: "16:00", home: "Alemania",        away: "Costa de Marfil",  group: "E", venue: "Toronto"        },
  { day: "Sáb 20 jun", time: "22:00", home: "Ecuador",         away: "Curazao",          group: "E", venue: "Kansas City"    },
  { day: "Sáb 20 jun", time: "00:00", home: "Túnez",           away: "Japón",            group: "F", venue: "Monterrey"      },
  { day: "Dom 21 jun", time: "12:00", home: "España",          away: "Arabia Saudí",     group: "H", venue: "Atlanta"        },
  { day: "Dom 21 jun", time: "15:00", home: "Bélgica",         away: "Irán",             group: "G", venue: "Los Ángeles"    },
  { day: "Dom 21 jun", time: "18:00", home: "Uruguay",         away: "Cabo Verde",       group: "H", venue: "Miami"          },
  { day: "Dom 21 jun", time: "21:00", home: "Nueva Zelanda",   away: "Egipto",           group: "G", venue: "Vancouver"      },
  { day: "Lun 22 jun", time: "13:00", home: "Argentina",       away: "Austria",          group: "J", venue: "Dallas"         },
  { day: "Lun 22 jun", time: "17:00", home: "Francia",         away: "Irak",             group: "I", venue: "Filadelfia"     },
  { day: "Lun 22 jun", time: "20:00", home: "Noruega",         away: "Senegal",          group: "I", venue: "Nueva York/NJ"  },
  { day: "Lun 22 jun", time: "23:00", home: "Jordania",        away: "Argelia",          group: "J", venue: "San Francisco"  },
  { day: "Mar 23 jun", time: "13:00", home: "Portugal",        away: "Uzbekistán",       group: "K", venue: "Houston"        },
  { day: "Mar 23 jun", time: "16:00", home: "Inglaterra",      away: "Ghana",            group: "L", venue: "Boston"         },
  { day: "Mar 23 jun", time: "19:00", home: "Panamá",          away: "Croacia",          group: "L", venue: "Toronto"        },
  { day: "Mar 23 jun", time: "22:00", home: "Colombia",        away: "RD Congo",         group: "K", venue: "Guadalajara"    },

  // ── Jornada 3 ──
  { day: "Mié 24 jun", time: "15:00", home: "Suiza",           away: "Canadá",           group: "B", venue: "Vancouver"      },
  { day: "Mié 24 jun", time: "15:00", home: "Bosnia y Herz.",  away: "Catar",            group: "B", venue: "Seattle"        },
  { day: "Mié 24 jun", time: "18:00", home: "Escocia",         away: "Brasil",           group: "C", venue: "Miami"          },
  { day: "Mié 24 jun", time: "18:00", home: "Marruecos",       away: "Haití",            group: "C", venue: "Atlanta"        },
  { day: "Mié 24 jun", time: "21:00", home: "Rep. Checa",      away: "México",           group: "A", venue: "Cd. de México"  },
  { day: "Mié 24 jun", time: "21:00", home: "Sudáfrica",       away: "Rep. de Corea",    group: "A", venue: "Monterrey"      },
  { day: "Jue 25 jun", time: "16:00", home: "Curazao",         away: "Costa de Marfil",  group: "E", venue: "Filadelfia"     },
  { day: "Jue 25 jun", time: "16:00", home: "Ecuador",         away: "Alemania",         group: "E", venue: "Nueva York/NJ"  },
  { day: "Jue 25 jun", time: "19:00", home: "Japón",           away: "Suecia",           group: "F", venue: "Dallas"         },
  { day: "Jue 25 jun", time: "19:00", home: "Túnez",           away: "Países Bajos",     group: "F", venue: "Kansas City"    },
  { day: "Jue 25 jun", time: "22:00", home: "Turquía",         away: "Estados Unidos",   group: "D", venue: "Los Ángeles"    },
  { day: "Jue 25 jun", time: "22:00", home: "Paraguay",        away: "Australia",        group: "D", venue: "San Francisco"  },
  { day: "Vie 26 jun", time: "15:00", home: "Noruega",         away: "Francia",          group: "I", venue: "Boston"         },
  { day: "Vie 26 jun", time: "15:00", home: "Senegal",         away: "Irak",             group: "I", venue: "Toronto"        },
  { day: "Vie 26 jun", time: "20:00", home: "Cabo Verde",      away: "Arabia Saudí",     group: "H", venue: "Houston"        },
  { day: "Vie 26 jun", time: "20:00", home: "Uruguay",         away: "España",           group: "H", venue: "Guadalajara"    },
  { day: "Vie 26 jun", time: "23:00", home: "Egipto",          away: "Irán",             group: "G", venue: "Seattle"        },
  { day: "Vie 26 jun", time: "23:00", home: "Nueva Zelanda",   away: "Bélgica",          group: "G", venue: "Vancouver"      },
  { day: "Sáb 27 jun", time: "17:00", home: "Panamá",          away: "Inglaterra",       group: "L", venue: "Nueva York/NJ"  },
  { day: "Sáb 27 jun", time: "17:00", home: "Croacia",         away: "Ghana",            group: "L", venue: "Filadelfia"     },
  { day: "Sáb 27 jun", time: "19:30", home: "Colombia",        away: "Portugal",         group: "K", venue: "Miami"          },
  { day: "Sáb 27 jun", time: "19:30", home: "RD Congo",        away: "Uzbekistán",       group: "K", venue: "Atlanta"        },
  { day: "Sáb 27 jun", time: "22:00", home: "Argelia",         away: "Austria",          group: "J", venue: "Kansas City"    },
  { day: "Sáb 27 jun", time: "22:00", home: "Jordania",        away: "Argentina",        group: "J", venue: "Dallas"         },
];
